FROM node:lts-alpine3.20 as build-stage
WORKDIR /app
COPY package.json .
RUN npm config set registry https://registry.npmmirror.com/
RUN npm i -g pnpm
COPY . .
RUN pnpm i
RUN pnpm build

# production state
FROM node:lts-alpine3.20 as production-stage
COPY --from=build-stage /app/dist /app
COPY --from=build-stage /app/package.json /app/package.json
WORKDIR /app

RUN npm config set registry https://registry.npmmirror.com/
RUN npm i -g pnpm
RUN pnpm i --prod
EXPOSE 3000
CMD ["node", "/app/main.js"]
