services:
  mysql-container:
    image: mysql
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: conference_room_reserve_system
      MYSQL_ROOT_PASSWORD: shidi666
    networks:
      - common-network
  redis-container:
    image: redis
    networks:
      - common-network
  fe-app:
    image: fe-container:v1.0
    ports:
      - 80:80
    depends_on:
      - nest-app
    networks:
      - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./dockerfile
    depends_on:
      - mysql-container
      - redis-container
    # ports:
    #   - 3000:3000
    networks:
      - common-network
networks:
  common-network:
    driver: bridge